### ISSUE TITLE
Check if a directory is empty before running analysis

### ISSUE THREAD

**Issue by GuidoBR** [alanwillms/php-hound#24]
When I run php-hound in a empty directory, it starts running forever.

~/.composer/vendor/alanwillms/php-hound/bin/php-hound
Starting analysis
Running PHPCodeSniffer...

It should display a message like "Please provide an directory with PHP code".

**Comment by alanwillms** [comment]
@GuidoBR that's odd, it should be fixed by now.

Can you run `php-hound --version` and tell what version is installed?

**Comment by GuidoBR** [comment]
~/.composer/vendor/alanwillms/php-hound/bin/php-hound --version
Starting analysis
Running PHPCodeSniffer... Done!
Running PHPCopyPasteDetector... Done!
Running PHPMessDetector... PHP Fatal error:  Uncaught exception 'Sabre\Xml\LibXMLException' with message 'Document is empty
 on line 1, column 1' in /home/guido/.composer/vendor/sabre/xml/lib/Reader.php:75
Stack trace:
#0 /home/guido/.composer/vendor/alanwillms/php-hound/src/integration/PHPMessDetector.php(37): Sabre\Xml\Reader->parse()
#1 /home/guido/.composer/vendor/alanwillms/php-hound/src/integration/AbstractIntegration.php(69): phphound\integration\PHPMessDetector->convertOutput(Object(Sabre\Xml\Reader), Object(phphound\AnalysisResult))
#2 /home/guido/.composer/vendor/alanwillms/php-hound/src/integration/AbstractIntegration.php(43): phphound\integration\AbstractIntegration->parseOutput(Object(phphound\AnalysisResult))
#3 /home/guido/.composer/vendor/alanwillms/php-hound/src/Command.php(101): phphound\integration\AbstractIntegration->run(Object(phphound\AnalysisResult), '--version')
#4 /home/guido/.composer/vendor/alanwillms/php-hound/src/Command.php(67): phphound\Command->runAllAnalysisTools()
#5 /home/guido/.composer/vendor/alanwillms/php-hound/bi in /home/guido/.composer/vendor/sabre/xml/lib/Reader.php on line 75

**Comment by GuidoBR** [comment]
I did:

~/.composer/vendor/alanwillms/php-hound/bin/php-hound --version

And got:

Nothing to install or update

**Comment by alanwillms** [comment]
@GuidoBR I think you have an old version. Try to run this:

`composer global update alanwillms/php-hound`
